<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Art.Common\Art.Common.csproj" />
    <ProjectReference Include="..\Art.EF\Art.EF.csproj" />
    <ProjectReference Include="..\Art.DbTestsBase\Art.DbTestsBase.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.assert" />
    <PackageReference Include="xunit.v3.extensibility.core" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
