name: Check PR

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: 'recursive'
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          8.0.x
          10.0.x
    - name: Install dependencies
      run: dotnet restore src
    - name: Build
      run: dotnet build src --configuration Release --no-restore
    - name: Test
      run: dotnet test src --configuration Release --no-build --verbosity normal

  inspect:
    name: Code Inspections
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: 'recursive'
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          8.0.x
          10.0.x
    - name: Install JetBrains-InspectCode
      run: |
        dotnet new tool-manifest
        dotnet tool install JetBrains.ReSharper.GlobalTools
        dotnet tool restore
    - name: Generate SARIF file from JetBrains-InspectCode
      run: dotnet tool run jb inspectcode src/Art.slnx -o="inspection_results" -f="sarif;text" --absolute-paths --settings="src/Art.sln.DotSettings" -e=WARNING
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: inspection_results/report.sarif
        category: JetBrains-InspectCode
    - name: Check inspection outputs
      id: check_inspection_outputs
      run: echo "inspection_count=$(cat inspection_results/report.sarif | jq ".runs[0].results | length")" >> "$GITHUB_OUTPUT"
    - name: Run bongjo if inspection has outputs
      if: ${{ steps.check_inspection_outputs.outputs.inspection_count != '0' }}
      run: dotnet run --project tools/bongjo -- review --base-commit "${{ github.base_ref }}"--head-commit "${{ github.head_ref }}" --sarif-file inspection_results/report.sarif
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Mark run as failed if inspection has outputs
      if: ${{ steps.check_inspection_outputs.outputs.inspection_count != '0' }}
      run: exit 1
